### ISSUE TITLE
No centrality matches

### ISSUE THREAD

**Issue by deepy420** [Gridflare/lndpytools#12]
I created a fresh describegraph.json file and had the script generate its own improvecentrality.conf file, yet I still don't get any matches. Very odd.

I do see matches when I check a different tool:
https://www.moneni.com/nodematch?node=03cd502dee15bb9859a6d9c56a5608c1f76894736ec4cfec906eb025b7623293dc

Loaded graph. Number of nodes: 19004 Edges: 82124
Latest update in graph: Mon Oct 11 08:21:45 2021
Simplified graph. Number of nodes: 11871 Edges: 4423
Performing analysis for BitcoinRevolution
First filtering pass found 0 candidates for new channels
Running modified farness score calculations
Completed modified farness score calculations in 1.7s
Checking 1ML availability statistics
1ML availability filter selected 0 candidates for new channels in 0.0s
No candidates found, is your graph stale?
If issue persists, delete describegraph.json and improvecentrality.conf
Traceback (most recent call last):
  File "/Users/sandeep/scripts/lndpytools/improvecentrality.py", line 248, in <module>
    main()
  File "/Users/sandeep/scripts/lndpytools/improvecentrality.py", line 239, in main
    raise ValueError('No valid candidates')
ValueError: No valid candidates

**Comment by Gridflare** [comment]
I suggest waiting a couple of days for the graph data to readjust.
I think your node is simply very new and not up to date with all the gossip yet.

**Comment by deepy420** [comment]
That makes sense. Ok, thanks!

**Comment by deepy420** [comment]
9 days later and now only 1 match.

Loaded graph. Number of nodes: 20094 Edges: 84252
Latest update in graph: Wed Oct 20 03:49:32 2021
Simplified graph. Number of nodes: 13003 Edges: 7465
Performing analysis for BitcoinRevolution
First filtering pass found 1 candidates for new channels
Running modified farness score calculations
Completed modified farness score calculations in 2.8s
Checking 1ML availability statistics
Failed to fetch availability for 0316a0f72a6db1a4d6ac041778179f142f1e788a680cb417bbfc9871b40628bc95
1ML availability filter selected 0 candidates for new channels in 0.7s
No candidates found, is your graph stale?
If issue persists, delete describegraph.json and improvecentrality.conf
Traceback (most recent call last):
  File "scripts/lndpytools/improvecentrality.py", line 248, in <module>
    main()
  File "scripts/lndpytools/improvecentrality.py", line 239, in main
    raise ValueError('No valid candidates')
ValueError: No valid candidates

**Comment by Gridflare** [comment]
Are you running on Neutrino by chance? My node is also running into issues right now, and I highly suspect Neutrino at this point.

**Comment by deepy420** [comment]
I really have no idea how to inspect that data. I've uploaded the file here in case you have a moment to check it:
https://pubsharefiles.s3.amazonaws.com/describegraph.json

**Comment by Gridflare** [comment]
If you have used neutrino on your node at any point some channels will have unknown capacity values.
The workaround is to drop the graph with chantools and fetch the graph with include_unannounced.
[GraphFilters]includeunannouced has been added to improvecentrality.conf.
Make sure Neutrino is fully disabled and replaced with a full or pruned node first.

IMPORTANT:
Using chantools dropchannelgraph has side effects, all of your own channels will disappear from describgraph unless fetched with include_unannounced, which will also include your private channels, which may not be desirable. 
https://github.com/lightninglabs/chantools/issues/48
