### ISSUE TITLE
checkchannels: division by zero

### ISSUE THREAD

**Issue by C-Otto** [Gridflare/lndpytools#2]
```
Traceback (most recent call last):
  File "/home/bitcoin/scripts/lndpytools/./checkchannels.py", line 129, in <module>
    printcentralitydiffs(mynode, myneighbours)
  File "/home/bitcoin/scripts/lndpytools/./checkchannels.py", line 119, in printcentralitydiffs
    f'{theircentdelta/base_centralities[pub_key]:+6.1%}',
ZeroDivisionError: float division by zero
```

This happened after the graph analysis, after I've seen all but one of the nodes I was expecting to see.

**Comment by Gridflare** [comment]
Thanks for the report, this should now be fixed in ee9bd71
