### ISSUE TITLE
No longer works since Nov 1

### ISSUE THREAD

**Issue by beeforbacon** [Gridflare/lndpytools#23]
Was this possibly due to the LND bug?

`Fetching graph data from lnd
Loaded graph. Number of nodes: 17919 Edges: 77505
Latest update in graph: Tue Nov  1 06:13:26 2022 (1667301206)
Traceback (most recent call last):
  File "/home/bacon/lndpytools/improvecentrality.py", line 257, in <module>
    main()
  File "/home/bacon/lndpytools/improvecentrality.py", line 217, in main
    filtered_graph = GraphFilter(graph, pub_key, graph_filters).filtered_g
  File "/home/bacon/lndpytools/GraphFilter.py", line 24, in __init__
    self.filtered_g = self.filter_relevant_nodes()
  File "/home/bacon/lndpytools/GraphFilter.py", line 42, in filter_relevant_nodes
    raise RuntimeError('Graph is more than 6 hours old, results will be innaccurate')
RuntimeError: Graph is more than 6 hours old, results will be innaccurate
`

**Comment by Gridflare** [comment]
Could be related to the LND bug, I cannot replicate on my LND running 15.4.
What do you get from `lncli getinfo | grep synced`?

**Comment by beeforbacon** [comment]
Ran make install again (after git checkout) and now lndpytools is working again. Thank you! Will close.
