### ISSUE TITLE
improvecentrality.py : TypeError: unsupported operand type(s) for >>: 'str' and 'int'

### ISSUE THREAD

**Issue by 3cola** [Gridflare/lndpytools#7]
user@Standard-PC-Q35-ICH9-2110:~/dev/lndpytools$ python3 improvecentrality.py 
Loaded graph. Number of nodes: 14567 Edges: 61097
Latest update in graph: Thu Aug 12 19:22:18 2021
Simplified graph. Number of nodes: 9824 Edges: 33893
Performing analysis for xxxxxxxxx
Traceback (most recent call last):
  File "improvecentrality.py", line 510, in <module>
    newchannelcandidates = selectinitialcandidates(g, filters)
  File "improvecentrality.py", line 219, in selectinitialcandidates
    return [n['pub_key'] for n in
  File "improvecentrality.py", line 219, in <listcomp>
    return [n['pub_key'] for n in
  File "improvecentrality.py", line 220, in <lambda>
    filter(lambda n: filtercandidatenodes(n, graph, filters),
  File "improvecentrality.py", line 215, in filtercandidatenodes
    and calcavgchanage(nkey, graph, currblockheight) >= minavgchanageblks
  File "improvecentrality.py", line 166, in calcavgchanage
    chanblk = chan['channel_id'] >> 40
TypeError: unsupported operand type(s) for >>: 'str' and 'int'

**Comment by 3cola** [comment]
changing line 166 of improvecentrality.py to:
chanblk = int(chan['channel_id']) >> 40
fixed the issue for me.

**Comment by Gridflare** [comment]
This was fixed in 40966ba2, please make sure you have the latest version
